spring:
  datasource:
    url: jdbc:h2:mem:sdv2024
    username: sdv2024
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate / update / create / create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

      h2:
        console:
          enabled: true
          path: /h2-console
          trace: false
          web-allow-others: false
